id = "coffeescript-zed"
name = "CoffeeScript"
version = "0.0.1"
schema_version = 1
authors = ["Sergii Kozak <svkozak@gmail.com>"]
description = "Coffeescript language server"
repository = "https://github.com/svkozak/coffeescript-zed"

[grammars.coffeescript]
repository = "file:////Users/admin/Dev/zed/tree-sitter-coffeescript"
rev = "b1dbaad94567dd4d321ac8fe53b556f2a1f3a87f"

[language_servers.coffeesense]
name = "CoffeeSense"
languages = ["CoffeeScript"]
command = "npx"
args = ["-y", "coffeesense-language-server@latest", "--stdio"]
